version: '3'
services:
  mongo:
    image: mongo
    container_name: mongodb
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  node-app:
    build: ./
    ports:
      - "3000:3000"
